name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 5.0.x
        - name: Restore dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --no-restore
        - name: Test
          run: 
            dotnet test test/CoverReport.A.Tests/CoverReport.A.Tests.csproj /p:CollectCoverage=true \
            #/p:ExcludeByAttribute="CompilerGeneratedAttribute" \
            #/p:Exclude='[*.Tests.*]*' \
            #/p:CoverletOutput='../results/' \
            #/p:CoverletOutputFormat=lcov%2cjson
            #/p:MergeWith='../results/coverage.json' \
        #- name: Code coverage to Coveralls
        #  uses: coverallsapp/github-action@master
        #  with:
        #    github-token: TzbZN58vs7nfWE4d9oB7ypq1CQsioBZwJ
        #    path-to-lcov: ./tests/Warren.Core.Invoice.BDD.Tests/results/coverage.info

    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 5.0.x
        - name: Restore dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --no-restore